before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: riPsYHGQhlGpj4im+/Xt0u/UtxYClnDD7MsLW0fDtTEzwjPawMc5r1PWz9q44YKHAl85igJ7y/qgZL4ptjCc3qE5SOY02daMScBH3FM9Zk+AFNxpPVBG1rBLvzYrr3o9VrTt5mN45iyXQd8MF4azDbCxS8B5IO1bPsiGn/jHP4KOmHsXTqPjpj+qmVU5+ArLchPMSWS6/SreWMcK3r093BlmCgpRVNcfP2AyeCbRnY5z2hD1qNZhIABye9BLGZxyaYEy9Wuy+BYD9X1R8vzTOax8bL9egAlAki9W8mtoG0jCZ+yq/PMRgot71wSfDSUnKAQRyomXdh7fpOte+a7tNmpDW8bFhLRVH9M8UJopmRwOKtUxviSKtFeD1pcL5SvYLzZhBqxnSoM/QzOB/qjg/ftUVpoE+fJK+QAdQJrj3NNjg7xgSsVovi9BJv+Q0I/Jy4Gf6bv42C7R6JQVGs92GxqqPCaLGUGulz7og6oO63Dt/8IRihXncStrxOYao685yX+1u2ZWDpNfiYHvWwICPuGPcDF7IqxEZPuRvjxnneETMGX1YjXQvdngUGdP1SjHdOnvgJhRvXY8gl0t+jIYFLPj4ZWeqdrWjf7a25VeRv6Xzn7VPLxZpWfBarH1MYpq6irRhMVpueFWNtCYf9BVd3H8cy61E4xbxbSkzmBYgWk= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
